name: CI for Java Invoice
on: [push]
jobs:
  test:
    name: Unit tests and check style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Test
        run: mvn test
      - name: Check style
        run: mvn checkstyle:check
